name: C app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc]

    steps:
    - name: Set up build env Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y build-essential

    - name: Set up build env Windows
      if: matrix.os == 'windows-latest'
      run: choco install mingw make

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build app
      run: |
        make linked
